import { writeFile } from 'node:fs/promises';
import path from 'node:path';

import { builtInCorpus } from '../repository/RuleSetLoader';
import { resolveExceptionVersions, resolveRuleVersions, toIsoDate } from '../rule-engine/VersionResolver';
import { validateRuleSet } from '../rule-engine/RuleSetValidator';

/**
 * Generates `RULE_DATA_QUALITY_REPORT.md`.
 *
 * A generator rather than a hand-written document, because a hand-written one
 * starts accurate and drifts. Every number below is counted from the corpus at
 * the moment of writing, so a report that says twelve unverified records means
 * there are twelve, today, in this build.
 *
 *   npm run rules:report
 */

const REFERENCE_DATE = process.argv[2] ?? '2026-09-01';

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => `| ${row.join(' | ')} |`).join('\n');
  return [head, rule, body].join('\n');
}

export function buildQualityReport(asOf: string = REFERENCE_DATE): string {
  const corpus = builtInCorpus();
  const day = toIsoDate(asOf);

  const report = validateRuleSet({
    rules: corpus.rules,
    exceptions: corpus.exceptions,
    amendments: corpus.amendments,
    sourceConflicts: corpus.sourceConflicts,
    ruleSetVersion: corpus.metadata.ruleSetVersion,
    ruleSetChecksum: corpus.metadata.checksum,
    asOf: day,
  });

  const inForce = resolveRuleVersions(corpus.rules, day);
  const exceptionsInForce = resolveExceptionVersions(corpus.exceptions, day);
  const future = corpus.rules.filter((rule) => toIsoDate(rule.effectiveFrom) > day);
  const expired = corpus.rules.filter((rule) => rule.effectiveTo !== null && toIsoDate(rule.effectiveTo) <= day);

  const verifiedAmendments = corpus.amendments.filter((entry) => entry.verificationStatus === 'VERIFIED');
  const partiallyVerified = corpus.amendments.filter((entry) => entry.verificationStatus === 'PARTIALLY_VERIFIED');
  const needsVerification = corpus.amendments.filter((entry) => entry.verificationStatus === 'NEEDS_VERIFICATION');
  const missingUrl = corpus.amendments.filter((entry) => !entry.officialSourceUrl);
  const missingEffectiveFrom = corpus.amendments.filter((entry) => entry.effectiveFrom === null);

  const needsLegalReview = [
    ...corpus.rules.filter((rule) => rule.interpretationStatus === 'NEEDS_LEGAL_REVIEW').map((rule) => `${rule.ruleId}@${rule.ruleVersion} — ${rule.title}`),
    ...corpus.exceptions
      .filter((entry) => entry.interpretationStatus === 'NEEDS_LEGAL_REVIEW')
      .map((entry) => `${entry.exceptionId}@${entry.effectiveFrom} — ${entry.title}`),
  ];

  const duplicateNotifications = corpus.amendments
    .map((entry) => entry.notificationNumber)
    .filter((value, index, all) => all.indexOf(value) !== index);

  const byChangeType = new Map<string, number>();
  for (const amendment of corpus.amendments) {
    byChangeType.set(amendment.changeType, (byChangeType.get(amendment.changeType) ?? 0) + 1);
  }

  const distinctRules = new Set(corpus.rules.map((rule) => rule.ruleId));
  const distinctExceptions = new Set(corpus.exceptions.map((entry) => entry.exceptionId));

  const lines: string[] = [];

  lines.push('# Rule Data Quality Report');
  lines.push('');
  lines.push('**Legal Metrology (Packaged Commodities) Rules, 2011 — versioned corpus**');
  lines.push('');
  lines.push(
    'Generated by `npm run rules:report`. Every figure is counted from the corpus at generation time; nothing here is maintained by hand.',
  );
  lines.push('');
  lines.push(
    `> This report describes the **quality of the legal data**, not the compliance of any package. Where a record is unverified or a reading is uncertain, it is listed below rather than smoothed over.`,
  );
  lines.push('');
  lines.push(
    table(
      ['', ''],
      [
        ['Rule-set version', `\`${corpus.metadata.ruleSetVersion}\``],
        ['Corpus checksum', `\`${corpus.metadata.checksum}\``],
        ['Reference date', day],
        ['Generated at', new Date().toISOString()],
      ],
    ),
  );
  lines.push('');

  /* ── Amendments ───────────────────────────────────────────────────────── */
  lines.push('## Amendment registry');
  lines.push('');
  lines.push(
    table(
      ['Metric', 'Count'],
      [
        ['Total amendment records', String(corpus.amendments.length)],
        ['Verified against the official Gazette PDF', String(verifiedAmendments.length)],
        ['Partially verified (effect established by another official document)', String(partiallyVerified.length)],
        ['Needs verification', String(needsVerification.length)],
        ['Missing official source URL', String(missingUrl.length)],
        ['Missing effective date', String(missingEffectiveFrom.length)],
        ['Duplicate notification numbers', String(duplicateNotifications.length)],
      ],
    ),
  );
  lines.push('');
  lines.push('### By change type');
  lines.push('');
  lines.push(
    table(
      ['Change type', 'Count'],
      [...byChangeType.entries()].sort((a, b) => b[1] - a[1]).map(([type, count]) => [type, String(count)]),
    ),
  );
  lines.push('');

  if (partiallyVerified.length > 0 || needsVerification.length > 0) {
    lines.push('### Records that are not fully verified');
    lines.push('');
    for (const amendment of [...partiallyVerified, ...needsVerification]) {
      lines.push(`- **${amendment.notificationNumber}** (${amendment.notificationDate}) — \`${amendment.verificationStatus}\``);
      lines.push(`  ${amendment.verificationNote ?? 'No note recorded.'}`);
    }
    lines.push('');
  }

  /* ── Rules ────────────────────────────────────────────────────────────── */
  lines.push('## Rule corpus');
  lines.push('');
  lines.push(
    table(
      ['Metric', 'Count'],
      [
        ['Distinct requirements (`ruleId`)', String(distinctRules.size)],
        ['Rule versions', String(corpus.rules.length)],
        [`In force on ${day}`, String(inForce.length)],
        [`Future-effective on ${day}`, String(future.length)],
        [`Superseded or expired by ${day}`, String(expired.length)],
        ['Missing source URL', String(corpus.rules.filter((rule) => !rule.source.officialUrl).length)],
        ['Interpretation marked NEEDS_LEGAL_REVIEW', String(corpus.rules.filter((rule) => rule.interpretationStatus === 'NEEDS_LEGAL_REVIEW').length)],
      ],
    ),
  );
  lines.push('');

  if (future.length > 0) {
    lines.push('### Future-effective rule versions');
    lines.push('');
    lines.push(
      'Notified but not yet in force. The engine must **not** apply these to an inspection dated before their commencement.',
    );
    lines.push('');
    lines.push(
      table(
        ['Rule', 'Version', 'Provision', 'In force from', 'Notification'],
        future
          .sort((a, b) => a.effectiveFrom.localeCompare(b.effectiveFrom))
          .map((rule) => [
            rule.ruleId,
            rule.ruleVersion,
            rule.sourceClause ?? rule.sourceSubRule ?? rule.sourceRule,
            rule.effectiveFrom,
            rule.source.notification,
          ]),
      ),
    );
    lines.push('');
  }

  /* ── Exceptions ───────────────────────────────────────────────────────── */
  lines.push('## Exemptions');
  lines.push('');
  lines.push(
    table(
      ['Metric', 'Count'],
      [
        ['Distinct exemptions (`exceptionId`)', String(distinctExceptions.size)],
        ['Exemption versions', String(corpus.exceptions.length)],
        [`In force on ${day}`, String(exceptionsInForce.length)],
        ['Full exemptions (NOT_APPLICABLE)', String(corpus.exceptions.filter((entry) => entry.effect === 'NOT_APPLICABLE').length)],
        ['Partial exemptions', String(corpus.exceptions.filter((entry) => entry.effect === 'PARTIAL_EXEMPTION').length)],
        ['Cross-regulation hand-offs', String(corpus.exceptions.filter((entry) => entry.effect === 'DEFER_TO_OTHER_REGULATION').length)],
      ],
    ),
  );
  lines.push('');

  /* ── Validation ───────────────────────────────────────────────────────── */
  lines.push('## Rule-set validation');
  lines.push('');
  lines.push(`Structural validity: **${report.valid ? 'PASS — no structural errors' : 'FAIL — structural errors present'}**`);
  lines.push('');
  lines.push(
    table(
      ['Severity', 'Count'],
      [
        ['Errors', String(report.counts.errors)],
        ['Warnings', String(report.counts.warnings)],
        ['Info', String(report.counts.info)],
      ],
    ),
  );
  lines.push('');

  const structural = report.conflicts.filter((entry) => entry.origin === 'STRUCTURAL');
  if (structural.length > 0) {
    lines.push('### Structural findings');
    lines.push('');
    for (const conflict of structural) {
      lines.push(`- \`${conflict.severity}\` **${conflict.code}** — ${conflict.message}`);
    }
    lines.push('');
  }

  /* ── Source conflicts ─────────────────────────────────────────────────── */
  lines.push('## Recorded source conflicts');
  lines.push('');
  lines.push(
    'Disagreements between official documents, or between the brief and the record. None of these can be resolved by this system; each is recorded with what the engine does in the meantime.',
  );
  lines.push('');
  for (const conflict of corpus.sourceConflicts) {
    lines.push(`### ${conflict.conflictId} — ${conflict.code} (\`${conflict.severity}\`)`);
    lines.push('');
    lines.push(conflict.message);
    lines.push('');
    if (conflict.documents) {
      for (const document of conflict.documents) {
        lines.push(`- **${document.notification}** — ${document.says}`);
        if (document.url) lines.push(`  <${document.url}>`);
      }
      lines.push('');
    }
    lines.push(`**Interim resolution.** ${conflict.interimResolution ?? 'None recorded.'}`);
    lines.push('');
    lines.push(`**Needs manual verification:** ${conflict.requiresManualVerification ? 'yes' : 'no'}`);
    lines.push('');
  }

  /* ── Open legal questions ─────────────────────────────────────────────── */
  lines.push('## Open questions of construction');
  lines.push('');
  if (needsLegalReview.length === 0) {
    lines.push('None recorded.');
  } else {
    lines.push('Records whose machine interpretation depends on a reading this system should not settle alone:');
    lines.push('');
    for (const entry of needsLegalReview) lines.push(`- ${entry}`);
  }
  lines.push('');

  /* ── Capability gaps ──────────────────────────────────────────────────── */
  lines.push('## Checks awaiting a capability this phase does not have');
  lines.push('');
  lines.push(
    'These rules are represented, sourced and dated, and their thresholds are in place. They cannot be evaluated because nothing in this phase measures an image, so they resolve to `INSUFFICIENT_EVIDENCE` — never to a pass and never to a violation.',
  );
  lines.push('');
  const pending = corpus.rules.filter((rule) => ['fontSize', 'placement', 'readability'].includes(rule.validation.kind));
  lines.push(
    table(
      ['Rule', 'Version', 'Provision', 'Measurement required'],
      pending.map((rule) => [
        rule.ruleId,
        rule.ruleVersion,
        rule.sourceClause ?? rule.sourceSubRule ?? rule.sourceRule,
        'requiresMeasurement' in rule.validation ? rule.validation.requiresMeasurement : '—',
      ]),
    ),
  );
  lines.push('');

  return `${lines.join('\n')}\n`;
}

async function main(): Promise<void> {
  const contents = buildQualityReport();
  const target = path.resolve(__dirname, '../../../RULE_DATA_QUALITY_REPORT.md');
  await writeFile(target, contents, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Wrote ${target}`);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exit(1);
  });
}
